### ISSUE TITLE
this project still maintain？

### ISSUE THREAD

**Issue by lyrl** [MuOnlineRepositories/MuOnline#1]

**Comment by apixandru** [comment]
It's not being actively developed. I come back to it from time to time but I'm not a very good mu server expert. I'm pretty much stuck.

I haven't really added new functionality to it, just refactored it a bunch so that it would be easier for people to start the server.

**Comment by lyrl** [comment]
do you know another good muonlike server project

**Comment by apixandru** [comment]
None that are stable.
This is more about learning than about having a robust server.

If you are interested in a robust server, check ragezone

**Comment by lyrl** [comment]
thank you 
> 在 2015年12月2日，17:02，Alexandru Constantin Bledea <notifications@github.com> 写道：
> 
> ragezone
